services:
  sonarqube:
    image: sonarqube:community
    container_name: sonar_server
    ports:
      - '9000:9000'
    # We use volumes to persist data so it doesn't vanish on restart
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
