
sonar.projectKey=queuebuzz-web
sonar.projectName=QueueBuzz Web
sonar.projectVersion=1.0

# Server Connection
sonar.host.url=http://localhost:9000

# Encoding
sonar.sourceEncoding=UTF-8

# Path to source directories
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.scannerwork/**,**/dist/**,**/tests/**

# Language Specifics
sonar.go.exclusions=**/vendor/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsx.lcov.reportPaths=coverage/lcov.info

# Exclude Annoying Rules
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.coverage.exclusions=**/*
# S1135: TODO tags
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
# S125: Commented out code
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
# S1186: Empty functions (common in Vue/React hooks)
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S1186
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*
